name: Publish to NPM
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to run the configuration step in"
        required: true
        default: "develop"
        options:
          - develop
          - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17.8.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: NODE_ENV=${{ github.event.inputs.environment}} npm ci && npm run build:final
      - name: Publish package on NPM 📦
        run:
          - npm config set git-tag-version=false
          - npm version $(git describe --tags) 
          - npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
