name: Publish to NPM
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to run the configuration step in"
        required: true
        default: "development"
        options:
          - production
          - development
          - none
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17.8.0"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies and build 🔧
        run: NODE_ENV=${{ github.event.inputs.environment }} npm ci && npm i webpack-cli && NODE_ENV=${{ github.event.inputs.environment}} npm run build:module
      - name: Publish package on NPM 📦
        run: npm config set git-tag-version=false && npm version $(git describe --tags) && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
